<?php

namespace App\Http\Requests\Admin;

use Illuminate\Foundation\Http\FormRequest;

class ArticleSaveRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'category_id' => [
                'required',
                'integer',
            ],
            'title'       => [
                'required',
                'string',
                'max:180'
            ],
            'body'        => [
                'required',
                'string',
                'max:10000'
            ],
            'date'        => [
                'required',
                'date'
            ],
            'is_publish'  => [
                'required',
                'boolean'
            ],
        ];
    }


    public function attributes()
    {
        // return parent::attributes(); // TODO: Change the autogenerated stub

        return [
            'category_id' => 'カテゴリー',
            'title'       => 'タイトル',
            'body'        => '本文',
            'date'        => '記事日付',
            'is_publish'  => '公開設定',
        ];
    }


}
